### ISSUE TITLE
release version 0.3.0 does not refference the new sdk but rather the old one

### ISSUE THREAD

**Issue by satanshiro** [launchdarkly/openfeature-node-server#28]
**Describe the bug**
if you look at the commit https://github.com/launchdarkly/openfeature-node-server/commit/9ef8d33c735a3a44a7f72e39e21db01ebed0ac62#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519
you will see that the release is still referencing an old version of launch darkly node js package named 'launchdarkly-node-server-sdk'
instead of '@launchdarkly/node-server-sdk'
this creates a typescript bug where basic functionality does not work
**To reproduce**
just create a typescript project running the quickstart you will get the error
`Argument of type 'import("/home/project/node_modules/@launchdarkly/node-server-sdk/dist/src/api/LDClient").LDClient' is not assignable to parameter of type 'import("launchdarkly-node-server-sdk").LDClient'.
  The types returned by 'waitForInitialization()' are incompatible between these types.
    Type 'Promise<import("/home/project/node_modules/@launchdarkly/js-server-sdk-common/dist/api/LDClient").LDClient>' is not assignable to type 'Promise<import("launchdarkly-node-server-sdk").LDClient>'.
      Type 'LDClient' is missing the following properties from type 'LDClient': bigSegmentStoreStatusProvider, on, addListener, emit, and 12 more`

**Expected behavior**
expect to be able to compile

**Logs**
If applicable, add any log output related to your problem.

**SDK version**
latest version

**Language version, developer tools**
typescript -node
**OS/platform**
wsl

**Additional context**
self explanatory

**Comment by kinyoklion** [comment]
The 0.3.0 release does not use the most recent major version of our node server SDK, as it was released before that SDK version. I can release a 0.4.0 that does use it though.

Thank you,
Ryan

**Comment by kinyoklion** [comment]
Version 0.4.0 has been released that uses `@launchdarkly/node-server-sdk`. 

Thank you,
Ryan

**Comment by satanshiro** [comment]
works thank you!
