### ISSUE TITLE
update dependency to use latest launch darkly

### ISSUE THREAD

**Issue by satanshiro** [launchdarkly/openfeature-node-server#34]
**Is your feature request related to a problem? Please describe.**
currently using latest sdk we get a warning 
![image](https://github.com/launchdarkly/openfeature-node-server/assets/38865738/084bc581-038c-4b94-9f49-2363c94d1728)

**Describe the solution you'd like**
update the peer dependencies

**Comment by kinyoklion** [comment]
Hello @satanshiro,

I will be updating these soon, along with some other updates.

Thank you.
Ryan

**Comment by kinyoklion** [comment]
@satanshiro This is released in 0.5.0. Please note there are a number of breaking changes if you were using 0.4.0.
